# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.

{
    "name": "Freight Management | Freight Shipping Management",
    "version": "19.0.0.0",
    "category": "Industry",
    'summary': 'Freight Transport Management Freight shipment management Freight insurance management Freight transportation Freight carriage Freight consignment Transport consignment Freight merchandise Freight shipping transport shipping Freight payload Freight delivery',
    "description": """The Freight Management odoo app helps businesses to streamline their freight operations and enhance their efficiency. It enables businesses to manage their transportation processes of land, ocean, and air from a single platform. The app allows users to create freight requests from the website and users can manage and convert booking requests into a shipment, all details will be added to shipments and also can add orders, packages, services, custom details, and create customer invoices and vendor bills for added service. Users can also track shipments by booking id or shipment number from the website.""",
    "author": "BROWSEINFO",
    'website': "https://www.browseinfo.com/demo-request?app=bi_freight_management&version=19&edition=Community",
    'price': 99,
    'currency': "EUR",
    "depends": ['account', 'stock', 'sale_management', 'contacts', 'product', 'website', 'fleet', 'hr'],
    "data": [
        'security/ir.model.access.csv',
        'data/freight_service_data.xml',
        'data/freight_operation_data.xml',
        'data/freight_booking_data.xml',
        'wizard/freight_service_invoice_bill_views.xml',
        'views/web_template_views.xml',
        'views/freight_port_views.xml',
        'views/freight_vessel_views.xml',
        'views/freight_airline_views.xml',
        'views/freight_incoterms_views.xml',
        'views/freight_package_views.xml',
        'views/freight_move_type_views.xml',
        'views/freight_order_views.xml',
        'views/freight_order_package_item_views.xml',
        'views/freight_order_package_views.xml',
        'views/freight_service_views.xml',
        'views/freight_route_package_views.xml',
        'views/freight_route_views.xml',
        'views/freight_booking_views.xml',
        'views/freight_operation_house_views.xml',
        'views/freight_operation_all_shipment_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'bi_freight_management/static/src/js/im_web_frontend.js',
        ],
    },
    "license": 'OPL-1',
    "application": True,
    "auto_install": False,
    "installable": True,
    'live_test_url':"https://www.browseinfo.com/demo-request?app=bi_freight_management&version=19&edition=Community",
    "images":['static/description/Banner.gif'],
}
